"""Database

Revision ID: 0677b560f3e2
Revises: 1350c45035a9
Create Date: 2024-10-22 15:08:15.365173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0677b560f3e2'
down_revision: Union[str, None] = '1350c45035a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories_108bit', sa.Column('title', sa.String(length=1024), nullable=True))
    op.add_column('categories_108bit', sa.Column('description', sa.String(length=16384), nullable=True))
    op.create_unique_constraint(None, 'categories_108bit', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories_108bit', type_='unique')
    op.drop_column('categories_108bit', 'description')
    op.drop_column('categories_108bit', 'title')
    # ### end Alembic commands ###
