"""Database change

Revision ID: 2743a25abbc7
Revises: 1385a1390386
Create Date: 2024-11-06 19:06:21.935060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2743a25abbc7'
down_revision: Union[str, None] = '1385a1390386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'url',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('categories_108bit', 'url',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('categories_108bit', 'description',
               existing_type=sa.VARCHAR(length=16384),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('categories_descriptions', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.alter_column('categories_descriptions', 'description',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('category_images', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.alter_column('internet_sites', 'url',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('manufacturers', 'description',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('product_attributes', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('product_attributes', 'value',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('products', 'url',
               existing_type=sa.VARCHAR(length=4096),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('products_descriptions', 'title',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               nullable=True)
    op.alter_column('products_documents', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               nullable=True)
    op.alter_column('products_images', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               nullable=True)
    op.alter_column('storage', 'folder',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('storage', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('urls_statistics', 'url',
               existing_type=sa.VARCHAR(length=8192),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls_statistics', 'url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=8192),
               existing_nullable=False)
    op.alter_column('storage', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('storage', 'folder',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products_images', 'name',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products_documents', 'name',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products_descriptions', 'title',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('products', 'url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=4096),
               existing_nullable=True)
    op.alter_column('product_attributes', 'value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('product_attributes', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('manufacturers', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('internet_sites', 'url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('category_images', 'name',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('categories_descriptions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=True)
    op.alter_column('categories_descriptions', 'title',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('categories_108bit', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=16384),
               existing_nullable=True)
    op.alter_column('categories_108bit', 'url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('categories', 'url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###
