"""Database

Revision ID: 6aa5f8e8fbe8
Revises: e0a57dd569e0
Create Date: 2024-10-22 15:51:45.729649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa5f8e8fbe8'
down_revision: Union[str, None] = 'e0a57dd569e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories_108bit', sa.Column('internet_site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories_108bit', 'internet_sites', ['internet_site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories_108bit', type_='foreignkey')
    op.drop_column('categories_108bit', 'internet_site_id')
    # ### end Alembic commands ###
