"""Database creation

Revision ID: 8dcfa572b3bd
Revises: ee129205894c
Create Date: 2024-11-06 17:29:53.459523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dcfa572b3bd'
down_revision: Union[str, None] = 'ee129205894c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products_descriptions', 'description',
               existing_type=sa.VARCHAR(length=4096),
               type_=sa.String(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products_descriptions', 'description',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=4096),
               existing_nullable=True)
    # ### end Alembic commands ###
