"""Database

Revision ID: 8f67f8a90766
Revises: 0677b560f3e2
Create Date: 2024-10-22 15:43:05.630913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f67f8a90766'
down_revision: Union[str, None] = '0677b560f3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_108bit_parent_id_fkey', 'categories_108bit', type_='foreignkey')
    op.create_foreign_key(None, 'categories_108bit', 'categories_108bit', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories_108bit', type_='foreignkey')
    op.create_foreign_key('categories_108bit_parent_id_fkey', 'categories_108bit', 'categories', ['parent_id'], ['id'])
    # ### end Alembic commands ###
