"""Database change

Revision ID: 905fae34ce59
Revises: 985bdc354f68
Create Date: 2024-11-16 19:27:54.394907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905fae34ce59'
down_revision: Union[str, None] = '985bdc354f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage', sa.Column('uuid', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage', 'uuid')
    # ### end Alembic commands ###
