"""Database

Revision ID: e0a57dd569e0
Revises: 8f67f8a90766
Create Date: 2024-10-22 15:45:42.088578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a57dd569e0'
down_revision: Union[str, None] = '8f67f8a90766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_108bit_title_key', 'categories_108bit', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('categories_108bit_title_key', 'categories_108bit', ['title'])
    # ### end Alembic commands ###
