"""Database change

Revision ID: eba29d76d2ac
Revises: 1451b58ac113
Create Date: 2024-11-12 18:23:36.619885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba29d76d2ac'
down_revision: Union[str, None] = '1451b58ac113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('equipment_lines_product_id_fkey', 'equipment_lines', type_='foreignkey')
    op.create_foreign_key(None, 'equipment_lines', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipment_lines', type_='foreignkey')
    op.create_foreign_key('equipment_lines_product_id_fkey', 'equipment_lines', 'equipment_lines', ['product_id'], ['id'])
    # ### end Alembic commands ###
