"""Database creation

Revision ID: ee129205894c
Revises: 5c85c445a6f7
Create Date: 2024-11-03 13:59:48.180889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee129205894c'
down_revision: Union[str, None] = '5c85c445a6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internet_site', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=8192), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urls_statistics')
    # ### end Alembic commands ###
